postrboi/postrapp/urls.py
from django.urls import path
from postrapp import views

app_name = "postrapp"

urlpatterns = [
    path("" , views.IndexView.as_view(), name="index_view") , 
    path("post" , views.CreateView.as_view() , name="create_view") , 
    path("tag/<str:tag_name>/" , views.TagView.as_view() , name="tag_view")
]

postrboi/postrboi/urls.py
from django.contrib import admin
from django.urls import path , include
import postrapp.urls
import userprofile.urls
import stats.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.default.urls')) , 
    path('' , include(postrapp.urls)) , 
    path('user/' , include(userprofile.urls)),
    path('stats/', include(stats.urls))

]

postrboi/stats/urls.py
from django.urls import path 
from stats.views import SiteView, UserView

app_name = "stats"

urlpatterns = [
    path("site" , SiteView.as_view() , name="site_stats_view") , 
    path("<str:username>" , UserView.as_view() , name="user_stats_view")
]

postrboi/userprofile/urls.py
from django.urls import path
from userprofile import views

app_name = "userprofile"

urlpatterns = [
    
    path("<str:username>" , views.profile_view , name="profile_view")
]

postrboi/postrapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
import urllib.request as urllib2

# Create your models here.

class Tag(models.Model) : 

    tag_creator = models.ForeignKey(User , on_delete=models.CASCADE)
    tag_name = models.CharField(unique=True, blank=True, max_length=8 , default="")
    tag_slug = models.SlugField(unique=True , max_length=50)
    tag_description = models.CharField(blank=True , max_length=128, default="")

    seen_count = models.IntegerField(default=0)
    clicked_count = models.IntegerField(default=0)
    reco_count = models.IntegerField(default=0)

    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.tag_name

    def save(self, *args, **kwargs):

        self.tag_name = self.tag_name.upper()

        if (self.tag_name == "") or (self.tag_name == "NO-TAG") : 
            self.tag_slug = "no-tag"
        else : 
            self.tag_slug = slugify(self.tag_name)

        if (self.pk is False) : 
            Tag.objects.create(tag_name=self.tag_name , tag_slug=self.tag_slug , tag_creator=self.tag_creator)

        return super(Tag , self).save(*args, **kwargs)

class Post(models.Model) : 

    poster = models.ForeignKey(User , on_delete=models.CASCADE)
    content = models.TextField(blank=False, null=False, max_length=150 , unique=True)
    article_hyperlink = models.URLField(unique=True)

    tag_1 = models.ForeignKey(Tag , on_delete=models.CASCADE , related_name="high_prio_tag" , blank=True , null=True)
    tag_2 = models.ForeignKey(Tag , on_delete=models.CASCADE , related_name="moderate_prio_tag", blank=True , null=True)
    tag_3 = models.ForeignKey(Tag , on_delete=models.CASCADE , related_name="low_prio_tag", blank=True , null=True)
    tag_4 = models.ForeignKey(Tag , on_delete=models.CASCADE , related_name="least_prio_tag", blank=True , null=True)
    
    seen_count = models.IntegerField(default=0)
    click_count = models.IntegerField(default=0)
    reco_count = models.IntegerField(default=0)

    created_date = models.DateTimeField(auto_now_add=True)

    def save(self, if_new_profile=False, *args , **kwargs):

        request = urllib2.urlopen(self.article_hyperlink)
        self.article_hyperlink = request.geturl() #checking for redirects

        return super(Post, self).save(*args, **kwargs)


    def __str__(self):
        return self.content

postrboi/postrapp/forms.py
from django import forms
from postrapp.models import Post , Tag

class CreatePostForm(forms.ModelForm) :

    tag_1 = forms.CharField(max_length=8, required=False)
    tag_2 = forms.CharField(max_length=8, required=False)
    tag_3 = forms.CharField(max_length=8, required=False)
    tag_4 = forms.CharField(max_length=8, required=False)

    content = forms.CharField(widget = forms.Textarea , max_length=256)
    article_hyperlink = forms.URLField(max_length=256)

    action = forms.CharField(max_length=10 , initial="post")

    def clean(self) : 

        cleaned_data = super(CreatePostForm , self).clean()

        print('cleaned_data before processing : ')
        print(cleaned_data)

        print('any(self.errors) : ')
        print(any(self.errors))

        cleaned_data['tag_1'] = Tag.objects.get(tag_name = cleaned_data.get('tag_1' , ''))
        cleaned_data['tag_2'] = Tag.objects.get(tag_name = cleaned_data.get('tag_2' , ''))
        cleaned_data['tag_3'] = Tag.objects.get(tag_name = cleaned_data.get('tag_3' , ''))
        cleaned_data['tag_4'] = Tag.objects.get(tag_name = cleaned_data.get('tag_4' , ''))

        print('cleaned_data AFTER processing : ')
        print(cleaned_data)

        return cleaned_data


    class Meta : 
        model = Post
        fields = ['content' , 'article_hyperlink' , 'tag_1' , 'tag_2' , 'tag_3' , 'tag_4']

class CreateTagForm(forms.ModelForm) : 

    tag_name = forms.CharField(max_length=8)
    tag_description = forms.CharField(widget = forms.Textarea , max_length=128 , required=False)
    action = forms.CharField(max_length=10 , initial="tag")

    def clean(self) : 
        
        cleaned_data = super(CreateTagForm , self).clean()

        print("cleaned TAG-data : ")
        print(cleaned_data)

        print('any(self.errors) : ')
        print(any(self.errors))

        return cleaned_data

    class Meta : 
        model = Tag
        fields = ['tag_name' , 'action' , 'tag_description']

postrboi/postrapp/views.py
from itertools import chain

from django.shortcuts import render , redirect
from django.urls import reverse
from django.views import View
from django.http import HttpResponse

from postrapp.models import Post , Tag
from postrapp.forms import CreatePostForm , CreateTagForm
# Create your views here.


class IndexView(View) : 

    def get(self , request) : 

        all_posts = Post.objects.all()
        print(all_posts)
        current_user = request.user

        return render(request , "postrapp/index.html" , context={"all_posts" : all_posts,
                                                                "current_user" : current_user
                                                                })

class CreateView(View) : 

    def get(self, request) : 

        post_form = CreatePostForm()
        tag_form = CreateTagForm()

        tags_by_user = Tag.objects.filter(tag_creator=request.user)

        return render(request , "postrapp/create.html" , context={'post_form':post_form , 'user':request.user , 
                                                                    'tag_form':tag_form , 'current_user':request.user , 
                                                                    'tags_by_user':tags_by_user}) 

    def post(self , request) : 
        
        print("the request is : ")
        print(request.POST)

        if request.POST.get("action" , "") == 'post' : 

            post_form = CreatePostForm(request.POST)

            print(request.POST)

            if post_form.is_valid() : 

                post = post_form.save(commit=False)
                post.poster = request.user
                post.save()
                return redirect(reverse('postrapp:index_view'))

            else : 

                return HttpResponse("Whoops something went wrong...<br><br>"+post_form.errors)

        elif request.POST.get("action" , "") == 'tag' :

            tag_form = CreateTagForm(request.POST)

            print(request.POST)
            
            if tag_form.is_valid() : 

                tag = tag_form.save(commit=False)
                tag.tag_creator = request.user
                tag.save()
                return redirect(reverse('postrapp:index_view'))
            
            else : 

                return HttpResponse("Whoops something went wrong...<br><br>"+tag_form.errors)

        else : 

            return HttpResponse("What tomfuckery have you been upto?")

class TagView(View) : 

    def get(self , request , tag_name) :
        
        tag = Tag.objects.get(tag_name = tag_name.upper())

        all_posts = chain(Post.objects.filter(tag_1 = tag),Post.objects.filter(tag_2 = tag) , \
                    Post.objects.filter(tag_3 = tag) , Post.objects.filter(tag_4 = tag))

        context = {"all_posts" : all_posts , "tag" : tag, "current_user":request.user}

        return render(request , "postrapp/view_tag.html" , context=context)

postrboi/templates/postrapp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>PostrBoi</title>
        
        {% include "postrapp/snippets/css_links.html" %}

    </head>
    <body>

   
        <!-- navbar -->
        {% include "postrapp/snippets/navbar.html" with current_user=current_user %}

        <!--  content  -->
        {% block content %}
        {% endblock %}

        <!-- footer -->
        {% include "postrapp/snippets/footer.html" %}

        <!-- scripts -->
        {% include "postrapp/snippets/scripts.html" %}
        

    </body>
</html>

postrboi/templates/postrapp/create.html
{% extends 'postrapp/base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block content %}

<div class="container">

    <div class="row">

        <div class="col-md-9 col-sm-12">

            <h1 class="display-2">P0ST</h1>
            <form action="{% url 'postrapp:create_view'%}" method="POST" class="my-2">
                {% csrf_token %}

                <div class="row">
                    <div class="col-12 form-group">
                        {% render_field post_form.content class="col-12" id="post-text" placeholder="why do you think I should click this post?"%}
                        <!-- <textarea id="post-text"  class="col-12" placeholder="why do you think I should click this post?"></textarea> -->
                    </div>
                </div>

                <div class="row pb-2">
                    <div class="col-12 text-center">
                        
                        {% render_field post_form.article_hyperlink type="text" class="input-field form-control text-light text-mono" placeholder="article_hyperlink"%}
                        <!-- <input type="text" class="input-field form-control text-light text-mono" placeholder="article_hyperlink"> -->
                    </div>
                </div>

                <div class="row post-author-tags  align-items-center p3-3">

                    <div class="col-2 text-center">
                        {% render_field post_form.tag_1 type="text" class="input-field form-control text-light text-mono"  placeholder="tag"%}
                        <!-- <input type="text" class="input-field form-control text-light text-mono"  placeholder="tag">                         -->
                    </div>

                    <div class="col-2 text-center">
                        {% render_field post_form.tag_2 type="text" class="input-field form-control text-light text-mono"  placeholder="tag"%}
                        <!-- <input type="text" class="input-field form-control text-light text-mono"  placeholder="tag"> -->
                    </div>

                    <div class="col-4 text-center text-mono">
                         <span class="input-field form-control" style="border-style:none;">{{user}}</span>
                    </div>

                    <div class="col-2 text-center">
                        {% render_field post_form.tag_3 type="text" class="input-field form-control text-light text-mono"  placeholder="tag"%}
                        <!-- <input type="text" class="input-field form-control text-light text-mono"  placeholder="tag"> -->
                    </div>

                    <div class="col-2 text-center">
                        {% render_field post_form.tag_4 type="text" class="input-field form-control text-light text-mono"  placeholder="tag"%}
                        <!-- <input type="text" class="input-field form-control text-light text-mono"  placeholder="tag"> -->
                    </div>

                </div>

                <div hidden>
                    {% render_field post_form.action value="post" %}
                </div>

                <div class="row py-2  align-items-center">

                    <div class="col-3"> </div>
                    <div class="col-6 text-center"><button class="text-success text-mono btn btn-danger btn-shadow px-3 my-2 ml-0" type="submit">CREATE POST</button></div>
                    <div class="col-3"> </div>
                    
                </div>

            </form>
        </div>

        <div class="col-md-3 col-sm-12">
            <h1 class="display-2">TAG</h1>
            <form action="" method="POST">
                {% csrf_token %}


                <div class="form-group mb-5 row justify-content-center">

                    {% render_field tag_form.tag_name class="form-control input-field text-mono text-light col-12 mb-3" placeholder="create_tag" aria-label="Tag Name" aria-describedby="basic-addon2"%}
                    {% render_field tag_form.tag_description class="form-control input-field text-mono text-light col-12 mb-3" rows="2" placeholder="tag_description" %}
                    <div hidden>
                        {% render_field tag_form.action value="tag" %}
                    </div>
                    <div class="input-group-append">
                      <button class="text-success text-mono btn btn-danger btn-shadow" type="submit">cre8 tag</button>
                    </div>
                </div>

            </form>
            


            <div class="list-group mb-4">
                <div class="list-group-item text-mono input-field text-success"><b>tags-you-created : </b></div>
                {% for tag in tags_by_user %}
                <a href="{% url 'postrapp:tag_view' tag.tag_slug %}" class="list-group-item list-group-item-action text-mono input-field">{{tag.tag_name}}</a>
                {% endfor %}
            </div>

            <div class="input-group">
                <div class="input-group mb-2">
                    <input type="text" class="form-control input-field text-mono text-light" placeholder="search_tags">
                    <div class="input-group-append">
                        <a href="#!" class="btn btn-outline-success btn-shadow">
                            <span class="fas fa-search"></span>
                        </a>                          
                    </div>
                </div>                  
            </div>
              

        </div>


    </div>


    

</div>


{% endblock %}

postrboi/templates/postrapp/index.html
{% extends 'postrapp/base.html' %}
{% load static %}


{% block content %}

    {% for post in all_posts %}
    <div class="container">
        <div class="card text-white mb-3 index-card" style="min-width: 500px;">

            
            <!-- post content -->
            <div class="row align-items-center post-content">            
                    <div class="col-12">
                        <a href="{{post.article_hyperlink}}" class="index-hyperlink">
                        <p class="card-text text-center text-mono index-hyperlink" >{{ post.content }}</p>
                        </a>
                    </div>
            </div>

            <!-- post author and tags -->
            <div class="row post-author-tags">
                <div class="col-lg-2 d-none d-lg-block text-center" ><a href="{% url 'postrapp:tag_view' post.tag_1.tag_slug %}" class="tag-text-index-view tag-1">{{post.tag_1.tag_name}}</a></div>
                <div class="col-lg-2 col-md-4 col-sm-3 d-none d-sm-block text-center text-mono" ><a href="{% url 'postrapp:tag_view' post.tag_2.tag_slug %}" class="tag-text-index-view tag-2">{{post.tag_2.tag_name}}</a></div>
                <div class="col-md-4 col-sm-6 col-xs-12 text-center p-0 text-mono" > <a class="index-card-poster-name" href="{%url 'userprofile:profile_view' post.poster%}">{{post.poster}}</a></div>
                <div class="col-lg-2 col-md-4 col-sm-3 d-none d-sm-block text-center text-mono" ><a href="{% url 'postrapp:tag_view' post.tag_3.tag_slug %}" class="tag-text-index-view tag-3">{{post.tag_3.tag_name}}</a></div>
                <div class="col-lg-2 d-none d-lg-block text-center text-mono" ><a href="{% url 'postrapp:tag_view' post.tag_4.tag_slug %}" class="tag-text-index-view tag-4">{{post.tag_4.tag_name}}</a></div>
            </div>    

            <!-- post statistics -->
            <div class="row post-stats">
                <div class="col-lg-1 col-md-1 col-sm-2"><!-- empty space, for symmetry --></div>
                <div class="col-lg-10 col-md-10 col-sm-8 text-center">
                    <div class="row">
                        
                        <!-- on large and xlarge screens -->
                        <div class="col-4 d-none d-lg-block"><a class="text-success text-mono btn btn-outline-success btn-shadow px-3 my-2 ml-0" href="post.html">{SEEN_COUNT:{{post.seen_count}}}</a></div>
                        <div class="col-4 d-none d-lg-block"><a class="text-success text-mono btn btn-outline-primary btn-shadow px-3 my-2 ml-0" href="post.html">{CLICK_COUNT:{{post.click_count}}}</a></div>
                        <div class="col-4 d-none d-lg-block"><a class="text-success text-mono btn btn-outline-danger btn-shadow px-3 my-2 ml-0" href="post.html">{R3CC_COUNT:{{post.read_count}}}</a></div>
                        
                        <!-- on medium screens -->
                        <div class="col-4 d-md-block d-lg-none"><a class="text-success text-mono btn btn-outline-success btn-shadow px-3 my-2 ml-0" href="post.html">{{post.seen_count}}</a></div>
                        <div class="col-4 d-md-block d-lg-none"><a class="text-success text-mono btn btn-outline-primary btn-shadow px-3 my-2 ml-0" href="post.html">{{post.click_count}}</a></div>
                        <div class="col-4 d-md-block d-lg-none"><a class="text-success text-mono btn btn-outline-danger btn-shadow px-3 my-2 ml-0" href="post.html">{{post.read_count}}</a></div>
                    </div>
                </div>
                <div class="col-lg-1 col-md-1 col-sm-2"><!-- empty space, for symmetry --></div>
            </div>

            <!-- featured image -->
            <div class="row align-items-center post-bg-img" hidden>
                <div class="col-12 text-center">
                    <img class="img-fluid" src="{{post.image_hyperlink}}" alt="Card image cap">
                </div>
            </div>

        </div>
    </div>
    {% endfor %}


{% endblock %}

postrboi/templates/postrapp/view_tag.html
{% extends "postrapp/base.html" %}
{% load static %}


{% block content %}

    <div class="container h-100">

        <div class="row justify-content-center">
            <div class="col-12">
                <h4 class="userprofile-username ml-5">{{tag.tag_name}}</h4>
            </div>
            <div class="col-8 text-center">
                <p class="text-mono text-light text-center">
                    {{ tag.tag_description}}
                </p>
                <p class="col-md-12 text-mono text-center" style="opacity: 0.2;">Created by <a href="{% url 'userprofile:profile_view' tag.tag_creator.username %}" class="text-light">{{tag.tag_creator}}</a> </p>
            </div>
            <div class="row justify-content-center">
                        
                <!-- on large and xlarge screens -->
                <div class="col-4 d-none d-lg-block"><a class="text-success text-mono btn btn-outline-success btn-shadow px-3 my-2 ml-0" href="post.html">{SEEN_COUNT:0</a></div>
                <div class="col-4 d-none d-lg-block"><a class="text-success text-mono btn btn-outline-primary btn-shadow px-3 my-2 ml-0" href="post.html">{CLICK_COUNT:0}</a></div>
                <div class="col-4 d-none d-lg-block"><a class="text-success text-mono btn btn-outline-danger btn-shadow px-3 my-2 ml-0" href="post.html">{R3CC_COUNT:0}</a></div>
                
                <!-- on medium screens -->
                <div class="col-4 d-md-block d-lg-none"><a class="text-success text-mono btn btn-outline-success btn-shadow px-3 my-2 ml-0" href="post.html">0</a></div>
                <div class="col-4 d-md-block d-lg-none"><a class="text-success text-mono btn btn-outline-primary btn-shadow px-3 my-2 ml-0" href="post.html">0</a></div>
                <div class="col-4 d-md-block d-lg-none"><a class="text-success text-mono btn btn-outline-danger btn-shadow px-3 my-2 ml-0" href="post.html">0</a></div>

                <p class="text-mono stat-description"> . S T 4 T S . </p>  
            </div>
            
        </div>
        <hr>
        {% for post in all_posts %}
        <div class="container">
            <div class="card text-white mb-3 index-card" style="min-width: 500px;">

                
                <!-- post content -->
                <div class="row align-items-center post-content">
                    <div class="col-12">
                        <p class="card-text text-center text-mono" >{{ post.content }}</p>
                    </div>
                </div>

                <!-- post author and tags -->
                <div class="row post-author-tags">
                    <div class="col-lg-2 d-none d-lg-block text-center text-mono" >{{post.tag_1}}</div>
                    <div class="col-lg-2 col-md-4 col-sm-3 d-none d-sm-block text-center text-mono" >{{post.tag_2}}</div>
                    <div class="col-md-4 col-sm-6 col-xs-12 text-center p-0 text-mono" > <a href="#">{{post.poster}}</a></div>
                    <div class="col-lg-2 col-md-4 col-sm-3 d-none d-sm-block text-center text-mono" >{{post.tag_3}}</div>
                    <div class="col-lg-2 d-none d-lg-block text-center text-mono" >{{post.tag_4}}</div>
                </div>    

                <!-- post statistics -->
                <div class="row post-stats">
                    <div class="col-lg-1 col-md-1 col-sm-2"><!-- empty space, for symmetry --></div>
                    <div class="col-lg-10 col-md-10 col-sm-8 text-center">
                        <div class="row">
                            
                            <!-- on large and xlarge screens -->
                            <div class="col-4 d-none d-lg-block"><a class="text-success text-mono btn btn-outline-success btn-shadow px-3 my-2 ml-0" href="post.html">{SEEN_COUNT:{{post.seen_count}}}</a></div>
                            <div class="col-4 d-none d-lg-block"><a class="text-success text-mono btn btn-outline-primary btn-shadow px-3 my-2 ml-0" href="post.html">{CLICK_COUNT:{{post.click_count}}}</a></div>
                            <div class="col-4 d-none d-lg-block"><a class="text-success text-mono btn btn-outline-danger btn-shadow px-3 my-2 ml-0" href="post.html">{R3CC_COUNT:{{post.read_count}}}</a></div>
                            
                            <!-- on medium screens -->
                            <div class="col-4 d-md-block d-lg-none"><a class="text-success text-mono btn btn-outline-success btn-shadow px-3 my-2 ml-0" href="post.html">{{post.seen_count}}</a></div>
                            <div class="col-4 d-md-block d-lg-none"><a class="text-success text-mono btn btn-outline-primary btn-shadow px-3 my-2 ml-0" href="post.html">{{post.click_count}}</a></div>
                            <div class="col-4 d-md-block d-lg-none"><a class="text-success text-mono btn btn-outline-danger btn-shadow px-3 my-2 ml-0" href="post.html">{{post.read_count}}</a></div>
                        </div>
                    </div>
                    <div class="col-lg-1 col-md-1 col-sm-2"><!-- empty space, for symmetry --></div>
                </div>

                <!-- featured image -->
                <div class="row align-items-center post-bg-img" hidden>
                    <div class="col-12 text-center">
                        <img class="img-fluid" src="{{post.image_hyperlink}}" alt="Card image cap">
                    </div>
                </div>

            </div>
        </div>
    {% endfor %}


    </div>

    

    
    
{% endblock %}