postrboi/postrapp/urls.py
from django.urls import path
from postrapp import views

app_name = "postrapp"

urlpatterns = [
    path("" , views.IndexView.as_view(), name="index_view") , 
    path("post" , views.CreateView.as_view() , name="create_view") , 
    path("tag/<str:tag_name>/" , views.TagView.as_view() , name="tag_view")
]

postrboi/postrboi/urls.py
from django.contrib import admin
from django.urls import path , include
import postrapp.urls
import userprofile.urls
import stats.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.default.urls')) , 
    path('' , include(postrapp.urls)) , 
    path('user/' , include(userprofile.urls)),
    path('stats/', include(stats.urls))

]

postrboi/stats/urls.py
from django.urls import path 
from stats.views import SiteView, UserView

app_name = "stats"

urlpatterns = [
    path("site" , SiteView.as_view() , name="site_stats_view") , 
    path("<str:username>" , UserView.as_view() , name="user_stats_view")
]

postrboi/stats/models.py
from django.db import models

# Create your models here.

postrboi/stats/views.py
from django.shortcuts import render
from django.views.generic import View

from django.contrib.auth.models import User

# Create your views here.
class SiteView(View) : 

    def get(self , request) :
        current_user = request.user
        return render(request , "stats/site_stats.html" , context={"current_user":current_user})

class UserView(View) : 

    def get(self , request , username) : 
        
        user = User.objects.get(username=username)
        current_user = request.user

        return render(request , "stats/user_stats.html" , context={"user":user , "current_user" : current_user})

postrboi/templates/stats/snippets/css_links.html
{% load static %}


<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<link rel="stylesheet" href='{% static  "css/bootstrap4-neon-glow.min.css" %}'>
<link rel="stylesheet" href='{% static  "css/custom.css" %}'>
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@600&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Major+Mono+Display&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Monoton&display=swap" rel="stylesheet">
<link rel='stylesheet' href='//cdn.jsdelivr.net/font-hack/2.020/css/hack.min.css'>

postrboi/templates/stats/snippets/footer.html
{% load static %}

<div class="container">
    <div class="row fixed-bottom">
        <div class="col-12">
            <div class="float-right">
                <a href="{% url 'postrapp:create_view' %}">
                    <span class="hal-9000 d-block mr-5 mb-4 mt-3"></span>
                </a>
            </div>    
        </div>
    </div>
</div>

postrboi/templates/stats/snippets/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light d-block" id="mainNav">
  <div class="container">
    <a class="navbar-brand text-success text-mono" href="{% url 'postrapp:index_view' %}">PostrBo<span class="vim-caret">i</span></a>
    <button class="navbar-toggler navbar-toggler-right text-success text-mono" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">

      <ul class="navbar-nav ml-auto">
        
        <li class="nav-item mx-1 navbar-link my-1">
          <a href="{% url 'stats:site_stats_view' %}" class="nav-link btn btn-outline-dark text-mono text-success">Site Statistics</a>
        </li>
        
        
        <li class="nav-item mx-1 navbar-link my-1">
          <div class="btn-group nav-item w-100" >
            <button type="button" class="nav-link btn btn-outline-dark dropdown-toggle text-mono text-success rounded-0 w-100"" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="true">
              {{current_user}}
            </button>
            <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 38px, 0px);">
              <a class="dropdown-item text-success text-mono " href="{% url 'stats:user_stats_view' current_user.username%}">Your Statistics</a>
              <a class="dropdown-item text-success text-mono " href="#!">Account Credentials</a>
              <a class="dropdown-item text-success text-mono " href="#!">Report Issues</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item text-success text-mono " href="{%url 'auth_logout' %}">Log Out.</a>
            </div>
          </div>
        </li>        
        
      </ul>

    </div>
  </div>
</nav>

postrboi/templates/stats/snippets/scripts.html
{% load static %}


<div>
    <!-- <script src="{% static 'js/blog_custom.js'%}"></script> -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</div>